apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.name" . }}-svc
spec:
  selector:
    app: {{ include "helm.name" . }}

  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
